config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'users#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/registrations#new', as: :unauthenticated_root
    end
  end

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Post, user_id: user.id
    can :manage, Comment, user_id: user.id
    can :read, :all
    return unless user.admin?

    can :delete, Post
    can :delete, Comment
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_many :likes

  after_create :update_posts_counter

  validates :title, presence: true
  validates :title, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def update_posts_counter
    user.increment!(:post_counter)
  end

  def recent_five_comments
    comments.last(5)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts
  has_many :comments, through: :posts
  has_many :likes, through: :posts
  validates :name, presence: true
  validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_three_posts
    posts.includes(:comments, :likes).last(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def current_user
    User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post = Post.includes(:author, :comments, :likes).find(params[:post_id])
    comment = Comment.new(comment_params)
    comment.user = current_user
    comment.post = post
    if comment.save
      flash[:success] = 'Comment created successfully'
    else
      flash[:error] = 'Comment not created'
    end
    redirect_to user_post_path(current_user, post)
  end

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def destroy
    @comment = Comment.find(params[:id])
    @post = Post.find(@comment.post_id)
    @post.comments_counter -= 1
    @comment.destroy
    @post.save
    flash[:success] = 'You have deleted this comment!'
    redirect_to user_post_path(current_user, @post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.includes(:comments, :likes).find(params[:post_id])
    like = Like.new
    like.user = current_user
    like.post = post
    if like.save
      flash[:success] = 'Like created successfully'
    else
      flash[:error] = 'Like not created'
    end
    redirect_to user_post_path(current_user, post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
    render :new, locals: { post: @post }
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    respond_to do |format|
      format.html do
        if @post.save
          flash[:success] = 'Post created successfully'
          redirect_to user_posts_path(@user)
        else
          flash[:error] = 'Post not created'
          render :new, locals: { post: @post }
        end
      end
    end
  end

  def destroy
    post = Post.find(params[:id])
    user = User.find(post.user_id)
    user.posts_counter -= 1
    post.destroy
    user.save
    flash[:success] = 'You have deleted this post!'
    redirect_to user_posts_path(user)
  end

  private

  def post_params
    params.require(:new_post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/new.html.erb
<h1>Add Comment</h1>
<%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, scope: :comment, class: "form" do |form| %>
  <div class="mb-3">
    <%= form.label :text %>
    <%= form.text_area :text, class: "form-text" %>
  </div>
  <div class="mb-3">
       <%= form.submit "Add Post" %>
  </div>
<% end %>

app/views/confirmables/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/confirmables/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/partials/_comment.html.erb
<% comments.each do |comment| %>
  <li class='comment'><%= comment.author.name %> : <%= comment.text%>
  <% if can? :destroy, @comment %>
       <%= button_to 'Delete comment',
       user_post_comment_path(comment.author, comment.post,comment),
             method: :delete,
             data: {confirm: 'Are You Sure You Want to Delete This comment'}, class: 'btn btn-danger'%>
     <% end %>
  </li>
<% end %>

app/views/partials/_post.html.erb
<li>
  <div>
    <h3> <% post.title %> </h3>
    <p> <%= truncate(post.text, :length => 150) %> </p>
  </div>

  <div>
    <p>Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %> </p>
  </div>

</li>

<ul>
  <% post.recent_five_comments.each do |comment| %>
    <li>
      <span><%= comment.user.name %></span>
      <span><%= comment.text %></span>
    </li>
  <% end %>
</ul>

app/views/partials/_user.html.erb
<div class="user flex">
  <img src=<%= user.photo %> alt="Profile picture of <%= user.name%>" />
  <div class="user-stats flex">
    <h2><%= user.name %></h2>
    <small>
      <a href='/users/<%= user.id %>'>
        Number of Posts: <%= user.post_counter%>
      </a>
    </small>
  </div>
</div>

app/views/posts/index.html.erb
<section >
  <%= render'partials/user', user: @user %>
    <% @posts.each do |post| %>
        <ul>
          <%= render 'partials/post', post: post %>
        </ul>
    <% end %>
  <button type='button'>Pagination</button>
</section>

app/views/posts/new.html.erb
<h1>Create Post</h1>
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :new_post do |form| %>
  <div class="mb-3">
    <%= form.label :Subject %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :Comment %>
    <%= form.text_area :text, class: "form-control text" %>
  </div>
    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
    <%= form.submit %>
  </button>
<% end %>

app/views/posts/show.html.erb
<button><%= link_to 'Back', user_posts_path(@user.id) %></button>
<section>
  <div>
    <div>
      <h3> <%=@post.title%> by <%= @user.name%> </h3>
      <p> Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %> </p>
    </div>
    <h4> <%= @post.text%> </h4>
  </div>

  <% if can? :destroy, @post %>
       <%= button_to 'Delete Post',
             user_post_path,
             method: :delete,
             data: {confirm: 'Are You Sure You Want to Delete This Post'}%>
     <% end %>

  <ul>
    <%= form_with url: "/users/#{@post.user_id}/posts/#{@post.id}/likes" do |f| %>
    <button type="submit">
    likes
    </button>
  <% end %>

  <button>
    <%= link_to new_user_post_comment_path(@user.id, @post.id) do %>
   comments
  </button>
    <% end %>
  </ul>

    <div>
    <% @post.comments.each do |comment| %>
      <p> <%= comment.user.name%>: <%= comment.text%><p>
    <% end %>  
  </div>
</section>

app/views/users/index.html.erb
<h1> List all users </h1>
<div>
   <ul class='list'>
      <% @users.each do |user| %>
         <%= render 'partials/user', user: user %>

         <%= link_to 'users', user_path(user.id)%>
      <% end %>
   </ul>
</div>

app/views/users/show.html.erb
<div class="user-info flex">
  <%= render 'partials/user', user: @user %>

  <div class='bio'>
    <p><%= @user.bio %></p>
  </div>

  <div class='card'>
      <% @user.recent_three_posts.each do |post| %>
        <%= render 'partials/post', post: post %>
      <% end %>
  </div>

  <button>
    <%= link_to "See all posts", user_posts_path(user_id: @user.id)%>
  </button>
</div>